### ISSUE TITLE
Not all dependencies being installed

### ISSUE THREAD

**Issue by bkjones** [thelabnyc/django-oscar-cybersource#6]
I'm using Python 3.7 in a Linux docker container as well as on my local mac running Catalina. After installing django-oscar-cybersource, configuring it, and starting up my Django app, I consistently get an error that the 'suds' module cannot be found. In looking more closely, I can see that there is a 'suds-jurko' module that is referenced both in setup.py and in requirements.txt, but it is not in my site-packages directory in my virtual environment. 

I have run both pipenv and pip in clean environments, and neither of them are pulling down this requirement, or seemingly even detecting that it is a requirement at all. 

One issue I have with this is, of course, I don't understand how something in requirements.txt could go completely unmentioned by both pip and pipenv! However, a second issue is that this module seems to be specific to SOAP, and I'm not using the SOAP interface, so unless this is required for talking to the remote cybersource.com endpoints, I don't know why this module not found exception should even be triggered. 

Any pointers? Is anyone else able to replicate this? 

```
web_1  | 
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "/usr/local/lib/python3.7/threading.py", line 870, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
web_1  |     self.check(display_num_errors=True)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
web_1  |     include_deployment_checks=include_deployment_checks,
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
web_1  |     return checks.run_checks(**kwargs)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
web_1  |     new_errors = check(app_configs=app_configs)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
web_1  |     all_namespaces = _load_all_namespaces(resolver)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
web_1  |     url_patterns = getattr(resolver, 'url_patterns', [])
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 584, in url_patterns
web_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
web_1  |     return import_module(self.urlconf_name)
web_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1  |   File "/code/goodbody/urls.py", line 30, in <module>
web_1  |     path('api/cybersource/', include(apps.get_app_config('cybersource').urls[0])),
web_1  |   File "/usr/local/lib/python3.7/site-packages/oscar/core/application.py", line 144, in urls
web_1  |     return self.get_urls(), self.label, self.namespace
web_1  |   File "/usr/local/lib/python3.7/site-packages/cybersource/apps.py", line 15, in get_urls
web_1  |     from .views import (
web_1  |   File "/usr/local/lib/python3.7/site-packages/cybersource/views.py", line 15, in <module>
web_1  |     from .methods import Cybersource, Bluefin, create_review_order_note, mark_declined
web_1  |   File "/usr/local/lib/python3.7/site-packages/cybersource/methods.py", line 10, in <module>
web_1  |     from suds import sudsobject
web_1  | ModuleNotFoundError: No module named 'suds'
web_1  | 
^CGracefully stopping... (press Ctrl+C again to force)
```

**Comment by bkjones** [comment]
I've determined that setup.py has some dependencies listed as 'extra' that, it would appear, are actually required to run, like 'suds' above. Either that, or the documentation does not seem to mention (or I missed it?) what configuration controls whether or not soap is used. I can install these deps with pip individually myself, but I feel as though I must've missed something important, because having followed the install docs up to this point, I was missing the 'suds' module, and the 'soap' module, which were trying to be loaded upon startup of my django app.
